### PR TITLE
Update supported Python versions

### PR DESCRIPTION
**Pull request by hugovk**
Fixes https://github.com/sunspec/pysunspec/issues/65.

* Add support for Python 3.7 and 3.8

* Drop support for Python 3.3, EOL since 2017-09-29

* Drop support for Python 3.4, EOL since 2019-03-16

### CODE REVIEW

**Comment by altendky** [comment]
I don't run this repo and there hasn't been a response to my PRs...  but, I'd suggest breaking this up into separate PRs so they are easier to review and any issue with one will not hold up the others.

* There's already a 3.7 testing/docs PR #59.
* I suggested dropping 3.3 because it doesn't work with current tools and it is far past EOL.  3.4 is still running and is still a common minimum for py3 in 2/3 compatible projects and isn't EOL (even if admittedly not far off).  Maybe when it becomes an issue it'll be worth dropping support for it.

Side note, in case you like the various PRs I've got here, I have them (at least mostly) combined at the link below.  I've also got some model fixes.

https://github.com/altendky/pysunspec/tree/master_plus_pull_requests
https://github.com/altendky/models/tree/master_plus_pull_requests

**Comment by hugovk** [comment]
Thanks, I've created https://github.com/sunspec/pysunspec/pull/67 just for Python 3.3, and https://github.com/sunspec/pysunspec/pull/68 for just 3.3 and 3.4.

I've seen quite a few projects dropping support for 3.4 in anticipation of the EOL, as usage there is generally quite low:

* https://medium.com/@hugovk/python-version-share-over-time-3-1a2f2449efb2

(And other projects are dropping or preparing to drop 2.7 as well: https://python3statement.org/)

**Comment by altendky** [comment]
@hugovk, I certainly encourage people to not use py2 for new code and to have a plan for transitioning existing code to py3.  2-compatible libraries should certainly at least consider making an EOL plan of their own.  But, py2 will continue to exist in some form which we won't know until it happens.  I try to help the people that really can't change (and bug those who can to do so) so I'm not totally against retaining py2 support, at least for a few years or such given that there has been no statement yet.

**Comment by hugovk** [comment]
Updated to add support for Python 3.8.

* Passing build: https://travis-ci.org/hugovk/pysunspec/builds/623239497

**Comment by Kudrat9** [comment]
Added support for 3.7 and 3.8 separately

**Pull request closed without merging**
