### PR TITLE
Drop support for Python 3.3

### LINKED ISSUE #65: Drop Python 3.3 support?
Latest pip [doesn't support Python 3.3](https://github.com/pypa/pip/commit/90b3db476fa3723dd63d51b1d9ea3178addecc69#diff-2eeaed663bd0d25b7e608891384b7298).  CPython support for 3.3 [was dropped in September 2017](https://www.python.org/dev/peps/pep-0398/#lifespan).  Do we need to retain 3.3 support?

This came up over in #46 where I set Travis to update pip (and setuptools and wheel).  That isn't really related to the point of the PR so I've removed it.

### PR DESCRIPTION
**Pull request by hugovk**
Fixes #65.

### CODE REVIEW

**Comment by altendky** [comment]
This still has lots of unrelated changes.  Do we need three PR's for dropping versions?

https://github.com/sunspec/pysunspec/pull/66
https://github.com/sunspec/pysunspec/pull/67
https://github.com/sunspec/pysunspec/pull/68

**Comment by hugovk** [comment]
Of the three commits here, https://github.com/sunspec/pysunspec/pull/67/commits/aa1a7b9728c02f93b45bed2615eef85367d80de7 is probably the minimum (and the typo fixes can be left out too).

The other two commits are modernising things, some of which may only be possible when dropping 3.3, but aren't absolutely essential.

Would you like me to remove them?

---

As for multiple PRs, I understood from https://github.com/sunspec/pysunspec/pull/66#issuecomment-455897594 separate PRs were preferred to make things easier to review and prevent one from holding up the others.

Just let me know if you'd like any changes made to any of the three, and feel free to close any of them as well. Thanks!

**Comment by altendky** [comment]
I'm not a SunSpec employee, just another (hopeful) contributor like you.  I'm still looking to get interest in these repositories from SunSpec and I'm just trying to keep the issues/PRs a bit tidy for them.  If you have any contacts at SunSpec I'd welcome any help getting their attention.  I just sent an email to their general info address.

Yes, separate PRs are good for separate things.  Three for roughly the same thing and each doing multiple things is likely confusing.

I would probably end up with three PRs for now (and maybe a fourth dropping 3.3, I don't see much need to drop 3.4 yet).  One typo PR and another %->format PR.  If the latter fails 3.3 tests, so it goes (though I don't guess it will).  We will know it isn't usable until 3.3 is dropped at which point a catch-up merge will make the PR pass tests.  And then I guess another one for the test assertion changes.  Generally, they shouldn't have any overlap, each PR does one thing.  (hopefully I've kept mine tidy as well `:]` )

**Comment by hugovk** [comment]
Closing in favour of https://github.com/sunspec/pysunspec/pull/68, as 3.4 is also now EOL.

**Pull request closed without merging**
